### PR TITLE
(feat): Preserve marked script tags

### PR DESCRIPTION
**Pull request by ciddan**
Add ability to mark scripts as external, so that they do not get transformed. Useful for scripts loaded from CDN.

### CODE REVIEW

**Comment by Menci** [comment]
I think the current code handles external scripts correctly. It should be just transforming them to dynamic tags creation (to enforce script order).

So what's wrong currently?

**Comment by ciddan** [comment]
It currently prepends publicPath to all script tags, so
```html
<script src="https://cdn.jsdelivr.net/npm/systemjs@6.12.1/dist/system.js"></script>
```
is transformed to:
```javascript
__vitePluginPublicPath_addScriptTag({ "src": window.__publicPath + "https:\u002F\u002Fcdn.jsdelivr.net\u002Fnpm\u002Fsystemjs@6.12.1\u002Fdist\u002Fsystem.js" });
```
which results in the script tag pointing to:
https://mydomain.com/dist/https://cdn.jsdelivr.net/npm/systemjs@6.12.1/dist/system.js

**Comment by Menci** [comment]
Oh that seems to be a bug. I'll check it out later.

External scripts should be handled correctly without any attribute hint. So I may close this PR. Anyway thanks for catching.

**Comment by ciddan** [comment]
Sounds good!

**Comment by Menci** [comment]
I think it's fixed in https://github.com/Menci/vite-plugin-public-path/commit/2772a05859d994115cefe1ae9c2b3b03339242a0. Please test with v0.0.4.

**Comment by ciddan** [comment]
> I think it's fixed in [2772a05](https://github.com/Menci/vite-plugin-public-path/commit/2772a05859d994115cefe1ae9c2b3b03339242a0). Please test with v0.0.4.

Yup, fix looks good! Thanks for taking a look.

**Pull request closed without merging**
